version: "3.7"

services:
  vote:
    image: apshuk17/examplevotingapp_vote:latest
    networks: 
      - frontend
    depends_on:
      - redis

  redis:
    image: redis:5.0-alpine3.10
    networks:
      - frontend

  db:
    image: postgres:9.4
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  worker:
    image: apshuk17/examplevotingapp_worker:latest
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis

  result:
    image: apshuk17/examplevotingapp_result:latest
    networks:
      - backend
    depends_on:
      - db
    ports:
      - 5000:80

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      - vote
      - redis

networks:
  frontend:
  backend:

volumes:
  db-data:
